apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-mine
  namespace: nginx-mine
spec:
  interval: 5m
  chart:
    spec:
      chart: ./nginx-ingress
      version: '>1.0.x'
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
